### ISSUE TITLE
ForwardQueryResult is processed after full consumption with SQL Server

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#154]
Maybe you know what might be different with the SQL Server specific code so that this happens.
I am using the JPA API like the following:
`
List l = entityManager.createQuery("...").getResultList();
assertEquals(1, l.size());
assertNotNull(l.get(0));
`

The access to the first element i.e. `l.get(0)` triggers `ForwardQueryResult#advanceToEndOfResultSet` again but this time, it is already closed finally leading to a NPE.

**Comment by andyjefferson** [comment]
Nothing I can immediately think of in terms of difference between SQLServer and say, PostgreSQL. The size() call will call ForwardQueryResult.size() which will either do a COUNT query, or navigate to the end of the result set (see getSizeUsingMethod). More than likely the SQLServer JDBC driver is doing things differently re: closing.

**Comment by beikov** [comment]
Ahh, ok so I am also doing a `query.setMaxResults(1)`. Maybe you haven't implemented a strategy for doing that for SQL Server and fall back to a not maintained way of doing it?

**Comment by andyjefferson** [comment]
Yes, see https://github.com/datanucleus/datanucleus-rdbms/issues/25

**Comment by beikov** [comment]
Ok so I guess this reveals a problem with the fallback strategy of traversing the result set then?

**Comment by andyjefferson** [comment]
Not sure I can help on that without seeing the JPQL input and the SQL generated for it.

closeResults() is called when it gets to the "end", and that code would be met when using a query without range restriction (for all datastores).

**Comment by beikov** [comment]
Can you test with MSSQL? The query is roughly 
```
// Persist 1 Entity
List l = entityManager.createQuery(
        "SELECT e FROM Entity e WHERE e.id IN (SELECT e2.id FROM Entity e2)"
    )
    .setMaxResults(1)
    .getResultList();
assertEquals(1, l.size());
assertNotNull(l.get(0))
```

**Comment by andyjefferson** [comment]
No sorry, not got that datastore. If you can find out the stack trace for calling closeResults for example then can see whether it is closed in an expected way, or closed by the JDBC driver itself (and not catering for that possibility).

**Comment by beikov** [comment]
Here is the trace for when disconnect is called which effectively makes the `query` `null`
```
at org.datanucleus.store.query.AbstractQueryResult.disconnect(AbstractQueryResult.java:114)
	  at org.datanucleus.store.rdbms.query.AbstractRDBMSQueryResult.disconnect(AbstractRDBMSQueryResult.java:248)
	  at org.datanucleus.store.rdbms.query.JPQLQuery$2.managedConnectionPreClose(JPQLQuery.java:670)
	  at org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl.close(ConnectionFactoryImpl.java:519)
	  at org.datanucleus.store.connection.AbstractManagedConnection.release(AbstractManagedConnection.java:83)
	  at org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl.release(ConnectionFactoryImpl.java:353)
	  at org.datanucleus.store.rdbms.query.JPQLQuery.performExecute(JPQLQuery.java:746)
	  at org.datanucleus.store.query.Query.executeQuery(Query.java:1922)
	  at org.datanucleus.store.query.Query.executeWithMap(Query.java:1829)
	  at org.datanucleus.api.jpa.JPAQuery.getResultList(JPAQuery.java:203)
```

**Comment by beikov** [comment]
I suppose the problem occurs because there is no limit/offset implementation available for SQL Server, but might happen for every data store that has no "native" implementation.
Maybe if you set `applyRangeChecks` to false after calling `disconnect` might fix the issue. wdyt?

**Comment by beikov** [comment]
Apparently this has to do with the fact that I am not specifying an `order by` although I am using `setMaxResults`

**Comment by andyjefferson** [comment]
So if you have an order by with setMaxResults it operates successfully ? 
I'll have a try at reproducing it by creating a query like that and running it on say H2, but with DN code modified to disable the LIMIT/OFFSET code.

**Comment by andyjefferson** [comment]
OK, now get an NPE in 
java.lang.NullPointerException
        at org.datanucleus.store.rdbms.query.ForwardQueryResult$QueryResultIterator.hasNext(ForwardQueryResult.java:343)
        at org.datanucleus.store.rdbms.query.ForwardQueryResult.processNumberOfResults(ForwardQueryResult.java:141)
        at org.datanucleus.store.rdbms.query.ForwardQueryResult.advanceToEndOfResultSet(ForwardQueryResult.java:164)
        at org.datanucleus.store.rdbms.query.ForwardQueryResult.getSizeUsingMethod(ForwardQueryResult.java:512)
        at org.datanucleus.store.query.AbstractQueryResult.size(AbstractQueryResult.java:357)

by hacking the H2 adapter to disable the limit/offset. 
Also checked that it works fine when setting applyRangeChecks to false after close of the results. 
I'll look at better clean up on close of the resultSet

**Comment by andyjefferson** [comment]
GitHub master has the fix to applyRangeChecks, so please give it a try when convenient and, if it is indeed fixed for SQLServer as well, then I'll backport to 4.x

**Comment by beikov** [comment]
Yep is fixed now.
