### ISSUE TITLE
Support group by embeddable

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#226]
Currently, a query like `select a.embeddable, count(a.id) from A a group by a.embeddable` fails although it should work when *embeddable* is an attribute annotated with `@Embedded`. The error I get is

```
org.datanucleus.exceptions.NucleusException: Unable to create SQLExpression for mapping of type "org.datanucleus.store.rdbms.mapping.java.SerialisedMapping" since not supported
	at org.datanucleus.store.rdbms.sql.expression.SQLExpressionFactory.newExpression(SQLExpressionFactory.java:189)
	at org.datanucleus.store.rdbms.sql.expression.SQLExpressionFactory.newExpression(SQLExpressionFactory.java:155)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.processPrimaryExpression(QueryToSQLMapper.java:3106)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compilePrimaryExpression(AbstractExpressionEvaluator.java:183)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileUnaryExpression(AbstractExpressionEvaluator.java:172)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileAdditiveMultiplicativeExpression(AbstractExpressionEvaluator.java:151)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileRelationalExpression(AbstractExpressionEvaluator.java:126)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileOrAndExpression(AbstractExpressionEvaluator.java:68)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.evaluate(AbstractExpressionEvaluator.java:36)
	at org.datanucleus.query.expression.Expression.evaluate(Expression.java:338)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compileGrouping(QueryToSQLMapper.java:1101)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compile(QueryToSQLMapper.java:495)
	at org.datanucleus.store.rdbms.query.JPQLQuery.compileQueryFull(JPQLQuery.java:833)
	at org.datanucleus.store.rdbms.query.JPQLQuery.compileInternal(JPQLQuery.java:317)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1883)
	at org.datanucleus.store.query.Query.executeWithMap(Query.java:1829)
	at org.datanucleus.api.jpa.JPAQuery.getResultList(JPAQuery.java:203)
```

**Comment by andyjefferson** [comment]
Kindly define your test. Because I run this test 
[test.zip](https://github.com/datanucleus/datanucleus-rdbms/files/1280019/test.zip)
which seems to do all that your description says (class Person, with `@Embedded` class Address), it executes JPQL of
SELECT p.address, COUNT(p.id) FROM Person p GROUP BY p.address

and generates SQL of
SELECT P.CITY,P.STREET,COUNT(P.ID) FROM PERSON P GROUP BY P.CITY,P.STREET

**Comment by beikov** [comment]
Hmm, maybe it's fixed on master. I'll double check and maybe update the version is needed. I tested with 5.0.7

**Comment by beikov** [comment]
Can't test the exact scenario with 5.1 yet as some APIs changed since 5.0, but I tested with 5.0.9 too and had the same error. I'll let you know about the status when I can test with 5.1.

**Comment by beikov** [comment]
The reason was that I am setting `exclude-unlisted-classes` in the persistence.xml to `true` but am not listing the embeddable class as member in persistence.xml. I find it a bit unintuitive that the enhancer picks up the embeddable and reports it was enhanced, but apparently the runtime doesn't pick it up.
It is obviously required to declare the type, but when I do, I get an exception regarding an ElementCollection of that embeddable type as can be seen in this test:
[jpa-group-by-embeddable.zip](https://github.com/datanucleus/datanucleus-rdbms/files/1282271/jpa-group-by-embeddable.zip)

Stack trace is

```
org.datanucleus.store.rdbms.exceptions.NoTableManagedException: Persistent class "jpa.test.entities.NameObject" has no table in the database, but the operation requires it. Please check the specification of the MetaData for this class.
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:688)
	at org.datanucleus.store.rdbms.table.ColumnCreator.createColumnsForField(ColumnCreator.java:164)
	at org.datanucleus.store.rdbms.table.ColumnCreator.createColumnsForJoinTables(ColumnCreator.java:122)
	at org.datanucleus.store.rdbms.table.CollectionTable.initialize(CollectionTable.java:114)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.initializeClassTables(RDBMSStoreManager.java:3288)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:2897)
	at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:118)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.manageClasses(RDBMSStoreManager.java:1637)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.deleteSchemaForClasses(RDBMSStoreManager.java:4228)
	at org.datanucleus.store.schema.SchemaTool.deleteSchemaForClasses(SchemaTool.java:515)
	at org.datanucleus.PersistenceNucleusContextImpl.initialiseSchema(PersistenceNucleusContextImpl.java:1008)
	at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:485)
	at org.datanucleus.api.jpa.JPAEntityManagerFactory.initialiseNucleusContext(JPAEntityManagerFactory.java:935)
	at org.datanucleus.api.jpa.JPAEntityManagerFactory.initialise(JPAEntityManagerFactory.java:523)
	at org.datanucleus.api.jpa.JPAEntityManagerFactory.<init>(JPAEntityManagerFactory.java:420)
	at org.datanucleus.api.jpa.PersistenceProviderImpl.createEntityManagerFactory(PersistenceProviderImpl.java:112)
```

**Comment by andyjefferson** [comment]
Firstly, wrt to the original issue, if I don't put an entity in `<class>` and have exclude-unlisted-classes then I get an exception about class not being persistable, maybe it hasn't been enhanced.

Secondly, wrt an exception about schema generation, that is not what this issue is/was for. And when looking at your model I see that you have various fields in Document that have `@JoinTable` when they should have `@CollectionTable` ... `List<String>`, `List<NameObject>`, `Map<String, NameObject>` and `Map<String, String>`. While it is possible for a JPA provider to work around the users incorrect specification, and arguable that the spec should never have defined this different XXXTable annotation, the fact is that it did ... for non-entity and embeddable types.

**Comment by beikov** [comment]
Thanks for the hint, in fact, when using CollectionTable it works as expected. Still, it would be nice if DataNucleus could treat a JoinTable definition like a CollectionTable one. Hibernate for example implements this convenient behavior.

**Comment by andyjefferson** [comment]
That is already added, but not against this issue.

**Comment by beikov** [comment]
Thanks. I guess this can be closed then?
