### ISSUE TITLE
Support selecting map value

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#230]
A query like `select value(m) from Document d left join d.map m on key(m) = 1` fails when applied on the model
```
@Entity
class Document {
@Id @GeneratedValue Long id;
@OneToMany Map<Integer, Person> map;
}

@Entity
class Person {
@Id @GeneratedValue Long id;
String name;
}
```

The exception in this case happens during rollback/connection closing but also happens on access to the result list.
```
javax.persistence.PersistenceException: Exception thrown while loading remaining rows of query

	at org.datanucleus.api.jpa.JPAAdapter.getUserExceptionForException(JPAAdapter.java:533)
	at org.datanucleus.store.rdbms.query.ForwardQueryResult.closingConnection(ForwardQueryResult.java:310)
	at org.datanucleus.store.query.AbstractQueryResult.disconnect(AbstractQueryResult.java:105)
	at org.datanucleus.store.rdbms.query.AbstractRDBMSQueryResult.disconnect(AbstractRDBMSQueryResult.java:248)
	at org.datanucleus.store.rdbms.query.JPQLQuery$2.transactionPreClose(JPQLQuery.java:663)
	at org.datanucleus.store.connection.AbstractManagedConnection.transactionPreClose(AbstractManagedConnection.java:107)
	at org.datanucleus.store.connection.ConnectionManagerImpl$2.transactionPreRollBack(ConnectionManagerImpl.java:445)
	at org.datanucleus.TransactionImpl.internalPreRollback(TransactionImpl.java:518)
	at org.datanucleus.TransactionImpl.rollback(TransactionImpl.java:445)
	at org.datanucleus.api.jpa.JPAEntityTransaction.rollback(JPAEntityTransaction.java:131)
	at com.blazebit.persistence.testsuite.base.AbstractJpaPersistenceTest.destruct(AbstractJpaPersistenceTest.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.datanucleus.exceptions.NucleusException: You have just executed an SQL statement yet the information for the primary key column(s) is not available! Please generate a testcase and report this issue
	at org.datanucleus.store.rdbms.query.PersistentClassROF.getObject(PersistentClassROF.java:324)
	at org.datanucleus.store.rdbms.query.ResultClassROF.getObject(ResultClassROF.java:279)
	at org.datanucleus.store.rdbms.query.ForwardQueryResult.nextResultSetElement(ForwardQueryResult.java:188)
	at org.datanucleus.store.rdbms.query.ForwardQueryResult$QueryResultIterator.next(ForwardQueryResult.java:416)
	at org.datanucleus.store.rdbms.query.ForwardQueryResult.processNumberOfResults(ForwardQueryResult.java:143)
	at org.datanucleus.store.rdbms.query.ForwardQueryResult.advanceToEndOfResultSet(ForwardQueryResult.java:171)
	at org.datanucleus.store.rdbms.query.ForwardQueryResult.closingConnection(ForwardQueryResult.java:298)
	... 32 more
```

**Comment by andyjefferson** [comment]
Using the following test 
[test.zip](https://github.com/datanucleus/datanucleus-rdbms/files/1281599/test.zip)
all works as expected. The SQL generated is
SELECT M.ID,M."NAME" FROM DOCUMENT D LEFT OUTER JOIN DOCUMENT_PERSON M_MAP ON D.ID = M_MAP.DOCUMENT_ID LEFT OUTER JOIN PERSON M ON M_MAP.MAP_ID = M.ID AND M_MAP.MAP_KEY = 1

which all looks fine to me, and accessing the results returns a Person object. Hence why a testcase is required, since you're doing something different ...

**Comment by beikov** [comment]
Was quite some work to reproduce the issue with a minimal test case but I finally accomplished it. Here you go [jpa-select-map-value.zip](https://github.com/datanucleus/datanucleus-rdbms/files/1282142/jpa-select-map-value.zip)
