### ISSUE TITLE
PostgreSQL : Exception thrown while persisting null in bytea column

### ISSUE THREAD

**Issue by ashutoshc** [datanucleus/datanucleus-rdbms#234]
## Bug Report
We have java byte[] column in application and bytea column in postgres for it. Following exception is thrown while trying to persist null in this column. Note non-nulls get persisted fine. On other DBs (mysql, oracle and derby) there is no issue either for null or non-null value for this column.

DN version: 4.1
Postgres version: 9.4.9, 9.4.12, 9.6
Postgres jdbc driver version: postgresql-9.4.1208.jre7.jar

org.postgresql.util.PSQLException: ERROR: column "BIT_VECTOR" is of type bytea but expression is of type oid
  Hint: You will need to rewrite or cast the expression.
  Position: 346
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:133)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:431)
	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:413)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:3363)
	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:3339)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2079)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1922)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1777)
	at org.datanucleus.ExecutionContextThreadedImpl.persistObject(ExecutionContextThreadedImpl.java:217)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:715)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:740)

**Comment by ashutoshc** [comment]
I suspect fix suggested similar to https://stackoverflow.com/questions/34128144/unable-to-insert-null-in-bytea-field-in-postgres needs to be made.

**Comment by andyjefferson** [comment]
Whatever you think the 'fix' is, all issues require a testcase, and docs say that 4.x is no longer developed.bthx

**Comment by andyjefferson** [comment]
Unreproduceable. I can persist a bytea column with null, and the INSERT statement is 
`INSERT INTO "PERSON" ("BYTEFIELD","NAME","ID") VALUES (<null>,<'First'>,<1>)`.

Kindly follow what the problem reporting template says and this can be reopened. Til that point it is closed.

**Comment by nlmarco** [comment]
I just encountered this problem with an embedded object. I don't know, if it also happens with a non-embedded object.

Here's a test demonstrating it: [co.codewizards.dnpgtest.zip](https://github.com/datanucleus/datanucleus-rdbms/files/4473206/co.codewizards.dnpgtest.zip)

Note: You need to adapt the file `/src/main/resources/persistence.postgresql.properties` and specify your PostgreSQL-server-coordinates. Then simply run `mvn clean install` and it fails with the following error:

```
org.postgresql.util.PSQLException: ERROR: column "signaturedata" is of type bytea but expression is of type oid
  Hinweis: You will need to rewrite or cast the expression.
  Position: 102
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:427)
	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:414)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4569)
	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4546)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2026)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1869)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1724)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)
	at co.codewizards.dnpgtest.PostgresqlTest.persistExampleEntityNoSignature(PostgresqlTest.java:51)
```
P.S.: I hope it was the correct approach to reopen this issue -- rather than opening a new one.

**Comment by nlmarco** [comment]
The same problem happens without embedding. Here's the test-case again -- extended (with both, embedded and non-embedded object): 
[co.codewizards.dnpgtest.zip](https://github.com/datanucleus/datanucleus-rdbms/files/4473502/co.codewizards.dnpgtest.zip)

**Comment by nlmarco** [comment]
I just found out that the error does _not_ occur, anymore, if I remove the annotation:
```
@Column(jdbcType="BLOB")
private byte[] binaryData;
```
Without the `jdbcType` being specified, it works. DN still creates the column in PostgreSQL as `bytea`.

I remember that I specified this `@Column(jdbcType="BLOB")`, because I encountered another error years ago (with a much older DN-version). I'll now try whether I can safely omit it or whether this breaks compatibility with my Derby-databases.

Anyway, I think specifying the `jdbcType="BLOB"` should not cause any error. This still is a bug.

**Comment by nlmarco** [comment]
Yes, I encounter errors with Derby -- cannot remove the jdbcType="BLOB". I now get this:
```
Caused by: ERROR X0X67: Columns of type 'LONG VARCHAR FOR BIT DATA' may not be used in CREATE INDEX, ORDER BY, GROUP BY, UNION, INTERSECT, EXCEPT or DISTINCT statements because comparisons are not supported for that type.
	... 19 more
```
Clearly, DN makes Derby use a "LONG VARCHAR FOR BIT DATA" instead of a "BLOB", if I do not explicitly state that it should use a "BLOB". Therefore, I leave the `jdbcType="BLOB"` and wait for the fix in DN to treat this properly in PostgreSQL.

In the meantime, I'll mask a null-byte[] by a byte[0] -- temporarily.

**Comment by andyjefferson** [comment]
Why not just look at which XXXColumnMapping is used in the different cases? (i.e look at the log for that column). Then you look at the class for that XXXColumnMapping, and see where setting to null is handled, and the answer may be evident

**Comment by nlmarco** [comment]
It seems to me that the method `setObject(...)` is the same as only the base-class `AbstractLargeBinaryColumnMapping` has an implementation -- the sub-classes (most notably `BlobColumnMapping`) have none.

All these methods call `ps.setNull(param, getJDBCType());` hence the only difference is the value returned by `getJDBCType()`.

Given the information in https://stackoverflow.com/questions/34128144/unable-to-insert-null-in-bytea-field-in-postgres (posted above), I assume that DN uses the JDBC-type 'BINARY' for PostgreSQL, if I do not specify any `@Column(jdbcType="BLOB")` annotation. That's why it works (the posting on stackoverflow mentions this as a workaround).

Given all this, I have no idea what's the proper way of solving the issue. It looks like a bug in the PostgreSQL-JDBC-driver. Thus, should we open a bug-report, there?

**Comment by andyjefferson** [comment]
Since PostgreSQL seemingly isn't capable of coping with a basic call like

`ps.setNull(someIndex, java.sql.Types.BLOB);`

then I would agree that PostgreSQL should be what "fixes" this. 
Clearly we could have something added to the (PostgreSQL) datastore adapter (when using BLOB and wanting to set to null) to dirty hack it to do like the linked thread 

`ps.setNull(someIndex, Types.OTHER);`

**Comment by davecramer** [comment]
hmmm https://github.com/pgjdbc/pgjdbc/blob/d0453b7582975438eb889082cffcfd8ebe6e3e4d/pgjdbc/src/test/java/org/postgresql/test/jdbc2/BlobTest.java#L76 seems to suggest the problem might be elsewhere

**Comment by nlmarco** [comment]
Given your comment about the *.orm-files in https://github.com/datanucleus/datanucleus-rdbms/issues/338 I just gave this approach a try, but it ended in this exception:

```
JDBC type BINARY declared for field "co.codewizards.dnpgtest.persistence.ExampleEntity2.binaryData" of java type java.io.Serializable cant be mapped for this datastore.
org.datanucleus.exceptions.NucleusException: JDBC type BINARY declared for field "co.codewizards.dnpgtest.persistence.ExampleEntity2.binaryData" of java type java.io.Serializable cant be mapped for this datastore.
	at org.datanucleus.store.rdbms.adapter.BaseDatastoreAdapter.getColumnMappingClass(BaseDatastoreAdapter.java:2257)
	at org.datanucleus.store.rdbms.mapping.MappingManagerImpl.createColumnMapping(MappingManagerImpl.java:1543)
	at org.datanucleus.store.rdbms.mapping.java.AbstractContainerMapping.prepareColumnMapping(AbstractContainerMapping.java:125)
	at org.datanucleus.store.rdbms.mapping.java.SingleFieldMapping.initialize(SingleFieldMapping.java:48)
	at org.datanucleus.store.rdbms.mapping.java.AbstractContainerMapping.initialize(AbstractContainerMapping.java:74)
	at org.datanucleus.store.rdbms.mapping.MappingManagerImpl.getMapping(MappingManagerImpl.java:667)
	at org.datanucleus.store.rdbms.table.ClassTable.manageMembers(ClassTable.java:545)
	at org.datanucleus.store.rdbms.table.ClassTable.manageClass(ClassTable.java:451)
	at org.datanucleus.store.rdbms.table.ClassTable.initializeForClass(ClassTable.java:1277)
	at org.datanucleus.store.rdbms.table.ClassTable.initialize(ClassTable.java:269)
```

I think you fixed the problem with your last commit, anyway, but I thought I can get this running properly (without workaround) with the older DN-version (the latest release). However, I tried different possibilities in `jdbc-type` and `sql-type` and none of them worked.

If I specify `jdbc-type="BINARY"` or `jdbc-type="BINARY" sql-type="BYTEA"`, I get the above error.

What am I doing wrong? Or is there no proper way for the latest DN-release and I have to wait for the next release containing the commit https://github.com/datanucleus/datanucleus-rdbms/commit/349cc59b025a4cefcf9b4d6f04e206f137f85058 ?

**Comment by andyjefferson** [comment]
You already said that if you didn't specify any JdbcType then it worked (presumably with the current release), hence when it uses the DEFAULT for PostgreSQL for type "byte[]" (namely LongVarBinaryColumnMapping instead of BlobColumnMapping). Or "LONGVARBINARY" if insisting on specifying the JdbcType. No, BINARY is not defined in PostgreSQLAdapter for "byte[]", left to people to add such things if they really want them)

**Comment by nlmarco** [comment]
Thanks a lot! I didn't know that the magic word is "DEFAULT" ;-) It seems to work fine, now. But tests are still running...

**Comment by andyjefferson** [comment]
FWIW the reason why we don't have BINARY defined as a supported type is that PostgreSQL JDBC driver doesn't accept its existence (see Schematool "dbinfo" mode).
