### ISSUE TITLE
@ElementCollection Set<String> fails to persist due to "Insert of object [...] using statement "INSERT INTO [...] VALUES (DEFAULT)" failed : The number of values assigned is not the same as the number of specified or implied columns."

### ISSUE THREAD

**Issue by krichter722** [datanucleus/datanucleus-rdbms#245]
A very simple

    @Id
    @GeneratedValue
    private Long id;
    @ElementCollection(fetch = FetchType.EAGER)
    private Set<String> nameSynonyms = new HashSet<>();

causes

```
WARNING: Insert of object "richtercloud.datanucleus.element.collection.nu2l.MyEntity@63475ace" using statement "INSERT INTO MYENTITY VALUES (DEFAULT)" failed : The number of values assigned is not the same as the number of specified or implied columns.
Exception in thread "main" javax.persistence.PersistenceException: Insert of object "richtercloud.datanucleus.element.collection.nu2l.MyEntity@63475ace" using statement "INSERT INTO MYENTITY VALUES (DEFAULT)" failed : The number of values assigned is not the same as the number of specified or implied columns.
	at org.datanucleus.api.jpa.NucleusJPAHelper.getJPAExceptionForNucleusException(NucleusJPAHelper.java:316)
	at org.datanucleus.api.jpa.JPAEntityManager.flush(JPAEntityManager.java:950)
	at richtercloud.datanucleus.element.collection.nu2l.NewMain.main(NewMain.java:24)
Caused by: java.sql.SQLSyntaxErrorException: The number of values assigned is not the same as the number of specified or implied columns.
	at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)
	at org.apache.derby.client.am.ClientConnection.prepareStatement(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:777)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:777)
	at org.datanucleus.store.rdbms.SQLController.getStatementForUpdate(SQLController.java:252)
	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:244)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4535)
	at org.datanucleus.state.StateManagerImpl.flush(StateManagerImpl.java:5735)
	at org.datanucleus.flush.FlushOrdered.execute(FlushOrdered.java:106)
	at org.datanucleus.ExecutionContextImpl.flushInternal(ExecutionContextImpl.java:4058)
	at org.datanucleus.ExecutionContextImpl.flush(ExecutionContextImpl.java:4004)
	at org.datanucleus.api.jpa.JPAEntityManager.flush(JPAEntityManager.java:946)
	... 1 more
Caused by: ERROR 42802: The number of values assigned is not the same as the number of specified or implied columns.
	at org.apache.derby.client.am.ClientStatement.completeSqlca(Unknown Source)
	at org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)
	at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)
	at org.apache.derby.client.net.NetStatementReply.readPrepareDescribeOutput(Unknown Source)
	at org.apache.derby.client.net.StatementReply.readPrepareDescribeOutput(Unknown Source)
	at org.apache.derby.client.net.NetStatement.readPrepareDescribeOutput_(Unknown Source)
	at org.apache.derby.client.am.ClientStatement.readPrepareDescribeOutput(Unknown Source)
	at org.apache.derby.client.am.ClientPreparedStatement.readPrepareDescribeInputOutput(Unknown Source)
	at org.apache.derby.client.am.ClientPreparedStatement.flowPrepareDescribeInputOutput(Unknown Source)
	at org.apache.derby.client.am.ClientPreparedStatement.prepare(Unknown Source)
	at org.apache.derby.client.am.ClientConnection.prepareStatementX(Unknown Source)
	... 14 more
```

when persisted with

```
EntityManagerFactory emf = Persistence.createEntityManagerFactory("richtercloud_datanucleus-element-collection-nu2l_jar_1.0-SNAPSHOTPU");
EntityManager em = emf.createEntityManager();
MyEntity myEntity = new MyEntity();
em.getTransaction().begin();
em.persist(myEntity);
em.flush();
em.getTransaction().commit();
em.close();
```

`@ElementCollection Set<String>` should be supported according to [the documentation](http://www.datanucleus.org/products/accessplatform_4_0/jpa/annotations.html#ElementCollection). Changing to `Collection<String>` doesn't help.

A SSCCE can be found at https://gitlab.com/krichter/datanucleus-element-collection-nu2l.

experienced with 5.1.4

**Comment by andyjefferson** [comment]
Using Derby that you used, and with the embedded driver, works fine for me (using current codebase). Similarly with H2.

Tables created as 
```
CREATE TABLE MYENTITY
(
    ID BIGINT NOT NULL generated always as identity (start with 1)
)
CREATE TABLE MYENTITY_NAMESYNONYMS
(
    MYENTITY_ID BIGINT NOT NULL,
    NAMESYNONYMS_ELEMENT VARCHAR(255) NOT NULL
)
```
and then insert is
`INSERT INTO MYENTITY VALUES (DEFAULT)`
which is correct.

So the only thing I can assume is you created a table with other columns to those. But then DEBUG would show you that

**Comment by krichter722** [comment]
> So the only thing I can assume is you created a table with other columns to those. But then DEBUG would show you that

Yes, using a network service instead of an embedded one was not a good idea, sorry. This issue is indeed caused by existing database structures. I assumed they'd be overwritten with `<property name="javax.persistence.schema-generation.database.action" value="drop-create"/>` in `persistence.xml`.

I pushed an example of a working setup in the `fix` branch of the SSCCE.
