### ISSUE TITLE
Validation annotations can cause invalid schema generation SQL

### ISSUE THREAD

**Issue by krichter722** [datanucleus/datanucleus-rdbms#246]
An entity which uses both validation and JPA annotations like

```
@Entity
public class MyEntity implements Serializable {
    private static final long serialVersionUID = 1L;
    public static final int IMAGE_COUNT_MAX = 5;
    @Id
    @GeneratedValue
    private Long id;
    @Size(max = IMAGE_COUNT_MAX, message = "Maximal " + IMAGE_COUNT_MAX + " images are allowed")
    @Basic
    @Lob
    private ArrayList<byte[]> imageData = new ArrayList<>();
```

causes the `max` value of `@Size` to be passed as length attribute of the `LONG VARCHAR FOR BIT DATA` which is invalid SQL in Apache Derby and thus results in

```
SEVERE: Error thrown executing CREATE TABLE MYENTITY
(
    ID BIGINT NOT NULL generated always as identity (start with 1),
    IMAGEDATA LONG VARCHAR FOR BIT DATA(5)
) : Syntax error: Encountered "(" at line 4, column 40.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered "(" at line 4, column 40.
    at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
    at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
    at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
    at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
    at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:291)
    at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:291)
    at org.datanucleus.store.rdbms.table.AbstractTable.executeDdlStatement(AbstractTable.java:849)
    at org.datanucleus.store.rdbms.table.AbstractTable.executeDdlStatementList(AbstractTable.java:800)
    at org.datanucleus.store.rdbms.table.AbstractTable.create(AbstractTable.java:522)
    at org.datanucleus.store.rdbms.table.AbstractTable.exists(AbstractTable.java:580)
    at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.performTablesValidation(RDBMSStoreManager.java:3447)
    at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:2969)
    at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:118)
    at org.datanucleus.store.rdbms.RDBMSStoreManager.manageClasses(RDBMSStoreManager.java:1672)
    at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:648)
    at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.getDatastoreClass(RDBMSPersistenceHandler.java:88)
    at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:123)
    at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4535)
    at org.datanucleus.state.StateManagerImpl.flush(StateManagerImpl.java:5735)
    at org.datanucleus.flush.FlushOrdered.execute(FlushOrdered.java:106)
    at org.datanucleus.ExecutionContextImpl.flushInternal(ExecutionContextImpl.java:4058)
    at org.datanucleus.ExecutionContextImpl.flush(ExecutionContextImpl.java:4004)
    at org.datanucleus.api.jpa.JPAEntityManager.flush(JPAEntityManager.java:946)
    at richtercloud.datanucleus.validation.schema.confusion.NewMain.main(NewMain.java:33)
Caused by: ERROR 42X01: Syntax error: Encountered "(" at line 4, column 40.
    at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
    at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
    at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
    at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
    at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
    at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
    at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
    ... 22 more
```

This is very unintuitive, but apparently [intended to be a feature](https://stackoverflow.com/questions/48610473/why-does-a-size-validation-annotation-influence-datanucleus-jpa-database-schema?noredirect=1#comment84220687_48610473). DataNucleus would be more intuitive if the usage of validation annotations for schema generation would be turned of by default. Since `columnDefinition` of `@Column` is ignored as well, there's at least the use case described above where there's no way to produce a valid schema and specify the intended validation annotations. The same should apply to JDO.

Regarding the bigger picture, I doubt that using validation annotations for JPA schema generation is a good idea, since they're technically two different things. I'd remove the feature completely.

An SSCCE can be found at https://gitlab.com/krichter/datanucleus-validation-schema-confusion.

experienced with 5.1.4

**Comment by andyjefferson** [comment]
See https://github.com/datanucleus/datanucleus-core/issues/278

Also note that Derby JDBC driver seemingly returns JDBC metadata as saying that this SQL type can take a precision, which it cant.
