### ISSUE TITLE
NPE in QueryToSQLMapper

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#254]
I'm not sure what's happening here, but the query I try to execute with the latest release 5.1.6 looks like the following.

```
SELECT 
  CASE 
    WHEN localized_locale_1.name IS NULL THEN localized_workflow_defaultLanguage_1.name
    ELSE localized_locale_1.name 
  END 
FROM Workflow workflow 
LEFT JOIN workflow.localized localized_locale_1 
  ON (KEY(localized_locale_1) = :locale) 
LEFT JOIN workflow.localized localized_workflow_defaultLanguage_1 
  ON (KEY(localized_workflow_defaultLanguage_1) = workflow.defaultLanguage)
```

The model looks like this:

```
@Entity
public class Workflow implements Serializable {
    @Id
    @GeneratedValue
    private Long id;
    @Basic(optional = false)
    private Locale defaultLanguage;
    @ElementCollection
    @CollectionTable(
        joinColumns = {
            @JoinColumn(
                name = "ID",
                referencedColumnName = "ID",
                nullable = false,
                insertable = false,
                updatable = false) })
    @MapKeyColumn(
        name = "LANGUAGE_CODE",
        length = 10,
        nullable = false,
        insertable = false,
        updatable = false)
    private Map<Locale, LocalizedEntity> localized = new HashMap<Locale, LocalizedEntity>();
}

@Embeddable
public class LocalizedEntity implements Serializable {
    @Column(
        name = "NAME",
        nullable = false,
        length = 255)
    private String name;
    @Column(
        name = "DESCRIPTION",
        nullable = false,
        length = 2500)
    private String description;
}
```

The stacktrace is this 
```
java.lang.NullPointerException
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.processParameterExpression(QueryToSQLMapper.java:4072)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.processParameterExpression(QueryToSQLMapper.java:3969)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compilePrimaryExpression(AbstractExpressionEvaluator.java:187)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileUnaryExpression(AbstractExpressionEvaluator.java:172)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileAdditiveMultiplicativeExpression(AbstractExpressionEvaluator.java:151)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileRelationalExpression(AbstractExpressionEvaluator.java:126)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileOrAndExpression(AbstractExpressionEvaluator.java:68)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.evaluate(AbstractExpressionEvaluator.java:36)
	at org.datanucleus.query.expression.Expression.evaluate(Expression.java:338)
	at org.datanucleus.query.expression.DyadicExpression.evaluate(DyadicExpression.java:72)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compileFromClassExpression(QueryToSQLMapper.java:2247)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compileFrom(QueryToSQLMapper.java:530)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compile(QueryToSQLMapper.java:466)
	at org.datanucleus.store.rdbms.query.JPQLQuery.compileQueryFull(JPQLQuery.java:817)
	at org.datanucleus.store.rdbms.query.JPQLQuery.compileInternal(JPQLQuery.java:316)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1927)
	at org.datanucleus.store.query.Query.executeWithMap(Query.java:1873)
	at org.datanucleus.api.jpa.JPAQuery.getResultList(JPAQuery.java:204)
```

**Comment by andyjefferson** [comment]
Not part of RDBMS plugin, since the problem is in generic query compilation. See https://github.com/datanucleus/datanucleus-core/issues/281
