### ISSUE TITLE
Parsing error in query

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-rdbms#255]
The following query on the latest release 5.1.6

```
SELECT 
  indexedNodesMany_0_1, 
  keyedNodesMany_default_1 
FROM Root r 
LEFT JOIN r.indexedNodesMany indexedNodesMany_0_1 
  ON (INDEX(indexedNodesMany_0_1) = 0) 
LEFT JOIN r.keyedNodesMany keyedNodesMany_default_1 
  ON (KEY(keyedNodesMany_default_1) = 'default')
```

with the model

```
@Entity(name = "Root")
public class Root {
    @Id
    private Integer id;
    @ManyToMany
    @JoinTable(name = "list_many_to_many")
    @OrderColumn(name = "join_table_list_index")
    private List<IndexedNode> indexedNodesMany = new ArrayList<>();
    @ManyToMany
    @JoinTable(name = "map_many_to_many")
    @MapKeyColumn(name = "join_table_map_key2", length = 10)
    private Map<String, KeyedNode> keyedNodesMany = new HashMap<>();
}

@Entity(name = "IndexedNode")
public class IndexedNode {
    @Id
    private Integer id;
}

@Entity(name = "KeyedNode")
public class KeyedNode {
    @Id
    private Integer id;
}
```

Results in the following exception

```
javax.persistence.PersistenceException: expected ')' at character 193 in "Root r LEFT JOIN r.indexedNodesMany indexedNodesMany_0_1 ON (INDEX(indexedNodesMany_0_1) = 0) LEFT JOIN r.keyedNodesMany keyedNodesMany_default_1 ON (KEY(keyedNodesMany_default_1) = 'default')"
	at org.datanucleus.api.jpa.NucleusJPAHelper.getJPAExceptionForNucleusException(NucleusJPAHelper.java:340)
	at org.datanucleus.api.jpa.JPAQuery.getResultList(JPAQuery.java:220)
Caused by: org.datanucleus.store.query.QueryCompilerSyntaxException: expected ')' at character 193 in "Root r LEFT JOIN r.indexedNodesMany indexedNodesMany_0_1 ON (INDEX(indexedNodesMany_0_1) = 0) LEFT JOIN r.keyedNodesMany keyedNodesMany_default_1 ON (KEY(keyedNodesMany_default_1) = 'default')"
	at org.datanucleus.query.compiler.JPQLParser.processPrimary(JPQLParser.java:1365)
	at org.datanucleus.query.compiler.JPQLParser.processUnaryExpression(JPQLParser.java:1221)
	at org.datanucleus.query.compiler.JPQLParser.processMultiplicativeExpression(JPQLParser.java:1154)
	at org.datanucleus.query.compiler.JPQLParser.processAdditiveExpression(JPQLParser.java:1125)
	at org.datanucleus.query.compiler.JPQLParser.processRelationalExpression(JPQLParser.java:582)
	at org.datanucleus.query.compiler.JPQLParser.processAndExpression(JPQLParser.java:565)
	at org.datanucleus.query.compiler.JPQLParser.processOrExpression(JPQLParser.java:546)
	at org.datanucleus.query.compiler.JPQLParser.processExpression(JPQLParser.java:535)
	at org.datanucleus.query.compiler.JPQLParser.processFromJoinExpression(JPQLParser.java:465)
	at org.datanucleus.query.compiler.JPQLParser.processFromExpression(JPQLParser.java:320)
	at org.datanucleus.query.compiler.JPQLParser.parseFrom(JPQLParser.java:91)
	at org.datanucleus.query.compiler.JavaQueryCompiler.compileFrom(JavaQueryCompiler.java:206)
	at org.datanucleus.query.compiler.JPQLCompiler.compile(JPQLCompiler.java:84)
	at org.datanucleus.store.query.AbstractJPQLQuery.compileGeneric(AbstractJPQLQuery.java:304)
	at org.datanucleus.store.query.AbstractJPQLQuery.compileInternal(AbstractJPQLQuery.java:365)
	at org.datanucleus.store.rdbms.query.JPQLQuery.compileInternal(JPQLQuery.java:235)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1927)
	at org.datanucleus.store.query.Query.executeWithMap(Query.java:1873)
	at org.datanucleus.api.jpa.JPAQuery.getResultList(JPAQuery.java:204)
```

**Comment by andyjefferson** [comment]
Nothing to do with RDBMS plugin, as shown by the stack trace. This is generic query compilation, which is part of datanucleus-core. See https://github.com/datanucleus/datanucleus-core/issues/282
