### ISSUE TITLE
org.datanucleus.store.rdbms.sql.SQLText.toSQL (SQLText.java:339) high stack usage

### ISSUE THREAD

**Issue by Tagar** [datanucleus/datanucleus-rdbms#256]
It seems org.datanucleus.store.rdbms.sql.SQLText.toSQL uses recursion which leads to huge 
stack usage on wider datasets. 

Below exception was produced by Apache Hive Meta Stores (for Oracle backend) when trying to 
move a table from one schema to another (through a cross-schema rename).

Is this right that deepness of ```org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
``` -> ```org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)``` recursion is O(N) when N is number of columns?

Would be great to remove recursion in that one place, if possible. 

```
ERROR	March 3, 2018 10:14 AM	RetryingHMSHandler	
[pool-7-thread-189]: java.lang.StackOverflowError
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:330)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
	at org.datanucleus.store.rdbms.sql.SQLText.toSQL(SQLText.java:339)
...

```

Thanks.

**Comment by Tagar** [comment]
https://github.com/datanucleus/datanucleus-rdbms/blob/700de10e28962f483d9ad6531213d90f3af797dd/src/main/java/org/datanucleus/store/rdbms/sql/SQLText.java#L339

This is the line that causes really high stack usage.

We have some Hive/Spark/Impala tables as wide as 6-10k columns. 
Apache Hive Metastore uses ```org.datanucleus.store.rdbms``` to store schema of those tables.

**Comment by andyjefferson** [comment]
Since you are person seeing this, then why not contribute something?

**Comment by Tagar** [comment]
Thanks @andyjefferson - I'd love to, not sure if I can.. 
I asked Cloudera Support to contribute and fix this, 
> Support Case 203682 - Hive NPE when trying to move/rename table to another schema

Hope they can figure this out. As a workaround they just suggested just to increase Xss.

**Comment by andyjefferson** [comment]
No testcase provided. No way of seeing this. Consequently closing it, as per all docs. If anyone comes across it and can be bothered to demonstrate/fix it then post back here and it can be re-opened.

**Comment by jacobdotcosta** [comment]
Hi Andy.

I'm having this exact same problem, but I'm not sure how I can pass you information. If I list the records of a table, in some situations I see the error.

What information can I provide besides the stack traces?

**Comment by andyjefferson** [comment]
If somebody can see this then they can equally get the code and debug their usage, and contribute something. It is open source for a reason

**Comment by Tagar** [comment]
@jacobdotcosta we worked around just by increasing java stack 
`-Xss`
