### ISSUE TITLE
java.util.ConcurrentModificationException at StatementClassMapping.getMemberNumbers during HashMap.initialize

### ISSUE THREAD

**Issue by dcheung2** [datanucleus/datanucleus-rdbms#402]
A `ConcurrentModificationException` could be threw when multiple threads initialize same HashMap field.

```
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at org.datanucleus.store.rdbms.query.StatementClassMapping.getMemberNumbers(StatementClassMapping.java:194)
	at org.datanucleus.store.rdbms.query.PersistentClassROF.getObject(PersistentClassROF.java:264)
	at org.datanucleus.store.rdbms.scostore.CollectionStoreIterator.<init>(CollectionStoreIterator.java:100)
	at org.datanucleus.store.rdbms.scostore.MapValueCollectionStore.iterator(MapValueCollectionStore.java:333)
	at org.datanucleus.store.types.SCOUtils.populateMapDelegateWithStoreData(SCOUtils.java:849)
	at org.datanucleus.store.types.wrappers.backed.HashMap.loadFromStore(HashMap.java:267)
	at org.datanucleus.store.types.wrappers.backed.HashMap.initialise(HashMap.java:217)
	at org.datanucleus.store.types.TypeManagerImpl.createSCOInstance(TypeManagerImpl.java:471)
	at org.datanucleus.store.rdbms.mapping.java.AbstractContainerMapping.replaceFieldWithWrapper(AbstractContainerMapping.java:442)
	at org.datanucleus.store.rdbms.mapping.java.AbstractContainerMapping.postFetch(AbstractContainerMapping.java:459)
	at org.datanucleus.store.rdbms.request.FetchRequest.execute(FetchRequest.java:502)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.fetchObject(RDBMSPersistenceHandler.java:316)
	at org.datanucleus.state.StateManagerImpl.loadFieldsFromDatastore(StateManagerImpl.java:1542)
	at org.datanucleus.state.StateManagerImpl.loadUnloadedFieldsInFetchPlan(StateManagerImpl.java:3897)
	at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:4112)
	at foo.bar.dnGetMap(ManagerStrategyPair.java)
	at foo.bar.getMap(ManagerStrategyPair.java)
```

when
- PropertyNames.PROPERTY_MULTITHREADED = false
- Each thread using their own `PersistenceManager` without sharing PersistenceManager / ExecutionContext.
- All threads are executing same method with different values.

It looks random and not sure how to reproduce.

Analysis
- `MapValueCollectionStore` (and other Stores), is singleton in `StoreManager`
- First thread call `MapValueCollectionStore.iterator`, `MapValueCollectionStore.getSQLStatementForIterator` create object `iteratorMappingDef` and initialize it in a synchronized block
- Another thread may read `StatementClassMapping.getMemberNumbers` while another thread doing `addMappingForMember`  

My Finding
Double-check locking bug pattern in `MapValueCollectionStore.iteratorStmtLocked`

Two threads reach https://github.com/datanucleus/datanucleus-rdbms/blob/d4072de544cc4e3cb778d5be1c5d581d13973b6f/src/main/java/org/datanucleus/store/rdbms/scostore/MapValueCollectionStore.java#L292 
and double initialize the `iteratorStmtLocked`, that the 2nd thread overwrite `iteratorMappingDef` with a blank object.

**Comment by andyjefferson** [comment]
No way of seeing this, and no contrib, so marking as wont fix until such a time as it is visible
