### ISSUE TITLE
Change List backing store code for indexed list to shift in bulk (single statement)

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-rdbms#414]
Backport from #413 on master branch.

With an indexed list we have an index column. Consequently whenever adding / removing from an indexed list at a position we need to shift all existing elements AFTER that position down to create space.

If we have a list of 10 elements using an index, and we do a List.remove(3) then we get
```
UPDATE B SET A_ID_OID=NULL, ORDERIDX=-1 WHERE A_ID_OID=1 AND ORDERIDX=3
UPDATE B SET ORDERIDX = ORDERIDX + -1 WHERE A_ID_OID=1 AND ORDERIDX=4
UPDATE B SET ORDERIDX = ORDERIDX + -1 WHERE A_ID_OID=1 AND ORDERIDX=5
UPDATE B SET ORDERIDX = ORDERIDX + -1 WHERE A_ID_OID=1 AND ORDERIDX=6
UPDATE B SET ORDERIDX = ORDERIDX + -1 WHERE A_ID_OID=1 AND ORDERIDX=7
UPDATE B SET ORDERIDX = ORDERIDX + -1 WHERE A_ID_OID=1 AND ORDERIDX=8
UPDATE B SET ORDERIDX = ORDERIDX + -1 WHERE A_ID_OID=1 AND ORDERIDX=9
```

whereas we ought to do
```
UPDATE B SET A_ID_OID=NULL, ORDERIDX=-1 WHERE A_ID_OID=1 AND ORDERIDX=3
UPDATE B SET ORDERIDX = ORDERIDX + -1 WHERE A_ID_OID=1 AND ORDERIDX>3
```

**Comment by chrisco484** [comment]
Is this bulk shifting enhancement meant to work for 1-m relationship Lists implemented via a join table in the RDBMS? Or does it only work for 1-m relationships using an FK only (i.e. no join table)?

I have a 1-m implemented as a join i.e. using <join/> XML metadata definition and when attempting to rearrange the ordering of items I get a BatchUpdateException due to a duplicate entry:

Caused by: org.datanucleus.store.rdbms.exceptions.MappedDatastoreException
	at org.datanucleus.store.rdbms.scostore.AbstractListStore.internalShiftBulk(AbstractListStore.java:615) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.scostore.JoinListStore.internalAdd(JoinListStore.java:263) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.scostore.AbstractListStore.add(AbstractListStore.java:125) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.flush.ListAddAtOperation.perform(ListAddAtOperation.java:50) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.flush.OperationQueue.performAll(OperationQueue.java:168) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.flushOperationsForBackingStore(ExecutionContextImpl.java:4120) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.store.rdbms.mapping.java.CollectionMapping.postUpdate(CollectionMapping.java:226) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.request.UpdateRequest.execute(UpdateRequest.java:493) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.updateObjectInTable(RDBMSPersistenceHandler.java:408) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.updateObject(RDBMSPersistenceHandler.java:382) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.state.StateManagerImpl.flush(StateManagerImpl.java:5902) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.flush.FlushOrdered.execute(FlushOrdered.java:106) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.flushInternal(ExecutionContextImpl.java:4068) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.flush(ExecutionContextImpl.java:4014) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.preCommit(ExecutionContextImpl.java:4189) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.transactionPreCommit(ExecutionContextImpl.java:729) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.TransactionImpl.internalPreCommit(TransactionImpl.java:397) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.TransactionImpl.commit(TransactionImpl.java:287) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:99) ~[datanucleus-api-jdo-5.2.9.jar:?]
	at com.sas.framework.expojo.jdo.JdoPersistenceProvider.commitTx(JdoPersistenceProvider.java:435) ~[expojo-jdo-3.2.1.jar:?]
	at com.sas.framework.expojo.PersistenceProvider.forceCommitTx(PersistenceProvider.java:212) ~[expojo-core-3.2.1.jar:?]
	at com.sas.framework.entity.OrgEntity.sortChildOrgs(OrgEntity.java:215) ~[sasentity-4.7.0.jar:?]
	at com.sas.framework.entity.OrgEntity.onChildUpdate(OrgEntity.java:177) ~[sasentity-4.7.0.jar:?]
	at com.sas.framework.entity.OrgEntity.addToChildOrgEntities(OrgEntity.java:336) ~[sasentity-4.7.0.jar:?]
	at com.sas.framework.entity.OrgEntity.setParentOrgEntity(OrgEntity.java:357) ~[sasentity-4.7.0.jar:?]
	at com.sas.framework.entity.OrgTypeMgr.createOrg(OrgTypeMgr.java:158) ~[sasentity-4.7.0.jar:?]
	at com.sas.av.ui.wicket.modal.AddSimpleOrgUnitForm.updateModel(AddSimpleOrgUnitForm.java:103) ~[classes/:?]
	at org.wicketstuff.modalx.ModalFormPanel$1.onSubmit(ModalFormPanel.java:66) ~[modalx-7.0-SNAPSHOT.jar:7.0-SNAPSHOT]
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:218) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1312) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.markup.html.form.Form.process(Form.java:976) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:797) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:174) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:155) ~[wicket-core-7.18.0.jar:7.18.0]
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:601) ~[wicket-core-7.18.0.jar:7.18.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258) ~[wicket-core-7.18.0.jar:7.18.0]
	... 46 more
Caused by: java.sql.BatchUpdateException: Duplicate entry '103-58' for key 'orgentity_childorgentities.PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_202]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_202]
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:853) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:795) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy33.executeBatch(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.bull.javamelody.JdbcWrapper.doExecute(JdbcWrapper.java:422) ~[javamelody-core-1.89.0.jar:1.89.0]
	at net.bull.javamelody.JdbcWrapper$StatementInvocationHandler.invoke(JdbcWrapper.java:142) ~[javamelody-core-1.89.0.jar:1.89.0]
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:300) ~[javamelody-core-1.89.0.jar:1.89.0]
	at com.sun.proxy.$Proxy34.executeBatch(Unknown Source) ~[?:?]
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeBatch(ParamLoggingPreparedStatement.java:366) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.SQLController.processConnectionStatement(SQLController.java:675) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:409) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.scostore.AbstractListStore.internalShiftBulk(AbstractListStore.java:606) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.scostore.JoinListStore.internalAdd(JoinListStore.java:263) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.scostore.AbstractListStore.add(AbstractListStore.java:125) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.flush.ListAddAtOperation.perform(ListAddAtOperation.java:50) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.flush.OperationQueue.performAll(OperationQueue.java:168) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.flushOperationsForBackingStore(ExecutionContextImpl.java:4120) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.store.rdbms.mapping.java.CollectionMapping.postUpdate(CollectionMapping.java:226) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.request.UpdateRequest.execute(UpdateRequest.java:493) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.updateObjectInTable(RDBMSPersistenceHandler.java:408) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.updateObject(RDBMSPersistenceHandler.java:382) ~[datanucleus-rdbms-5.2.12.jar:?]
	at org.datanucleus.state.StateManagerImpl.flush(StateManagerImpl.java:5902) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.flush.FlushOrdered.execute(FlushOrdered.java:106) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.flushInternal(ExecutionContextImpl.java:4068) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.flush(ExecutionContextImpl.java:4014) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.preCommit(ExecutionContextImpl.java:4189) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.ExecutionContextImpl.transactionPreCommit(ExecutionContextImpl.java:729) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.TransactionImpl.internalPreCommit(TransactionImpl.java:397) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.TransactionImpl.commit(TransactionImpl.java:287) ~[datanucleus-core-5.2.11.jar:?]
	at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:99) ~[datanucleus-api-jdo-5.2.9.jar:?]
	at com.sas.framework.expojo.jdo.JdoPersistenceProvider.commitTx(JdoPersistenceProvider.java:435) ~[expojo-jdo-3.2.1.jar:?]

I haven't got a minimalist Test Case yet but before I did that I thought I should check if bulk shift was meant to work for <join/> table implementations.

**Comment by chrisco484** [comment]
It looks like bulk shift is supported in join tables and implemented in JoinListStore.
