### ISSUE TITLE
Regression with SQL Server caused by #408

### ISSUE THREAD

**Issue by danhaywood** [datanucleus/datanucleus-rdbms#444]
Connecting to SQL Server 2016, we hit an NPE at this point:

![image](https://user-images.githubusercontent.com/1031625/176500549-dc1f91c3-e4f1-46ca-bb46-8f0e5b32bf0d.png)

The reason is that we are iterating over the collection of `IndexInfo`s held in the `RDBMSTableIndexInfo`.  This in turn is populated ultimately by `RDBMSSchemaHandler` whee the call `conn.getMetaData().getIndexInfo(...)` ultimately results in sp_statistics being called.

If I run the command that is submitted, I get:

![image](https://user-images.githubusercontent.com/1031625/176501032-49a8c625-4c04-4abf-8c5b-52c44ea10b1d.png)

you can see that the first row is type=0 is statistics, not an index, and note that the index name is null.  This is what causes the NPE.

Comparing 6.0.0-release to 6.0.0-M3 (which worked), can see that the released version has removed a filter, done in issue #408.:

![image](https://user-images.githubusercontent.com/1031625/176501316-777b5408-485c-405f-bef9-2888fb2aebb9.png)

So, unfortunately it would seem that this change made to support H2v2 ends up breaking SQL Server,  I think that the original code was more correct.

I think it should be enough to connect to SQL Server with an existing table, but with validate mode enabled.

Please NOTE that people are strongly encouraged to CONTRIBUTE features / fixes, since this is open source software. 

I could raise a PR to revert the change at least here, if you wish.

**Comment by nscuro** [comment]
@danhaywood Have you tested whether 6.0.1 resolves your issue? I think I am still experiencing it.

The offending lines are not in the `getExistingIndices` method (as modified in a08ed02), but in `getExistingCandidateKeys`: https://github.com/datanucleus/datanucleus-rdbms/blob/531c5546df17e375715a26c793bf50c35d503c0f/src/main/java/org/datanucleus/store/rdbms/table/TableImpl.java#L1031-L1037

For reference, this is the relevant stack trace:

```
SEVERE: An exception was thrown while adding/validating class(es) : Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "name" is null
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "name" is null
	at org.datanucleus.store.rdbms.identifier.AbstractIdentifierFactory.newIdentifier(AbstractIdentifierFactory.java:427)
	at org.datanucleus.store.rdbms.table.TableImpl.getExistingCandidateKeys(TableImpl.java:1041)
	at org.datanucleus.store.rdbms.table.TableImpl.validateCandidateKeys(TableImpl.java:640)
	at org.datanucleus.store.rdbms.table.TableImpl.validateConstraints(TableImpl.java:368)
	at org.datanucleus.store.rdbms.table.ClassTable.validateConstraints(ClassTable.java:3719)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.performTablesValidation(RDBMSStoreManager.java:3583)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:3024)
	at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:118)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.createSchemaForClasses(RDBMSStoreManager.java:3866)
	at org.datanucleus.store.schema.SchemaTool.createSchemaForClasses(SchemaTool.java:505)
	at org.datanucleus.PersistenceNucleusContextImpl.initialiseSchema(PersistenceNucleusContextImpl.java:822)
	at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:484)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:865)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:352)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:275)
```

The `indexInfo` in this case looks as follows:

![image](https://user-images.githubusercontent.com/5693141/188327100-1cc0575d-e300-4001-91f9-11e5d887ee63.png)
