### ISSUE TITLE
IdentifiableTypeImpl fails to retrieve PK information from MappedSuperClass

### ISSUE THREAD

**Issue by mkolesnikov** [datanucleus/datanucleus-rdbms#75]
Here are domains classes:
```java
@MappedSuperclass
public abstract class BaseEntity<ID extends Serializable> {
  @Id
  @Column(name = ID)
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQ_GEN)
  @SequenceGenerator(name = SEQ_GEN, allocationSize = 1)
  private ID id;

...
}

@Entity
public class Note extends BaseEntity<Long> {

}
```

Getting exception:
```
Caused by: java.lang.IllegalArgumentException: PK member is not of specified type (java.lang.Long). Should be java.io.Serializable
	at org.datanucleus.api.jpa.metamodel.IdentifiableTypeImpl.getId(IdentifiableTypeImpl.java:102)
	at org.datanucleus.api.jpa.metamodel.IdentifiableTypeImpl.getId(IdentifiableTypeImpl.java:79)
	at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation$IdMetadata.<init>(JpaMetamodelEntityInformation.java:249)
```

IdentifiableTypeImpl
```java
public <Y> SingularAttribute<? super X, Y> getId(Class<Y> cls)
{
...
        int pkPosition = cmd.getPKMemberPositions()[0];
        AbstractMemberMetaData mmd = cmd.getMetaDataForManagedMemberAtAbsolutePosition(pkPosition);
        
        // *BUG*: We come here with supertype, 
        // thus, it should be mmd.getType().isAssignableFrom(cls)
        if (cls.isAssignableFrom(mmd.getType()))
        {
            // User passed in the type of the field
            SingularAttribute attr = (SingularAttribute) attributes.get(mmd.getName());
            if (attr == null)
            {
                IdentifiableType supertype = getSupertype();
                if (supertype != null)
                {
                    // Relay to the supertype
                    return supertype.getId(cls);
                }
            }
            return attr;
        }
...
}
```

**Comment by andyjefferson** [comment]
This is nothing to do with datanucleus-rdbms. JPA metamodel is part of datanucleus-api-jpa. It still needs a testcase as per what the issue template says.
